on:
  push:
    branches:
    - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'dcars-client.spec'
          python_ver: '3.13'
          upload_exe_with_name: "dcars-client-lin_x86-64"
          options:

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'dcars-client.spec'
          python_ver: '3.13'
          upload_exe_with_name: "dcars-client-win_x86-64"
          options: 
