on:
  push:
    branches:
    - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'main.spec'
          upload_exe_with_name: "dcars-client-$GITHUB_SHA"
          options: --name "dcars-client"

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'main.spec'
          upload_exe_with_name: "dcars-client-$GITHUB_SHA"
          options: --name "dcars-client"
